import Computer from './computer';

const newComp = new Computer();
newComp.createCoords();

test('creates all coords', () => {
    expect(newComp.returnCoords()).toEqual({
        a1: null,
        a10: null,
        a2: null,
        a3: null,
        a4: null,
        a5: null,
        a6: null,
        a7: null,
        a8: null,
        a9: null,
        b1: null,
        b10: null,
        b2: null,
        b3: null,
        b4: null,
        b5: null,
        b6: null,
        b7: null,
        b8: null,
        b9: null,
        c1: null,
        c10: null,
        c2: null,
        c3: null,
        c4: null,
        c5: null,
        c6: null,
        c7: null,
        c8: null,
        c9: null,
        d1: null,
        d10: null,
        d2: null,
        d3: null,
        d4: null,
        d5: null,
        d6: null,
        d7: null,
        d8: null,
        d9: null,
        e1: null,
        e10: null,
        e2: null,
        e3: null,
        e4: null,
        e5: null,
        e6: null,
        e7: null,
        e8: null,
        e9: null,
        f1: null,
        f10: null,
        f2: null,
        f3: null,
        f4: null,
        f5: null,
        f6: null,
        f7: null,
        f8: null,
        f9: null,
        g1: null,
        g10: null,
        g2: null,
        g3: null,
        g4: null,
        g5: null,
        g6: null,
        g7: null,
        g8: null,
        g9: null,
        h1: null,
        h10: null,
        h2: null,
        h3: null,
        h4: null,
        h5: null,
        h6: null,
        h7: null,
        h8: null,
        h9: null,
        i1: null,
        i10: null,
        i2: null,
        i3: null,
        i4: null,
        i5: null,
        i6: null,
        i7: null,
        i8: null,
        i9: null,
        j1: null,
        j10: null,
        j2: null,
        j3: null,
        j4: null,
        j5: null,
        j6: null,
        j7: null,
        j8: null,
        j9: null,
    });
});

test('removes previous hits from options', () => {
    expect(newComp.removeCoords('a1')).toEqual({ a1: null });
});

test('checkAdjacent returns a valid adjacent square', () => {
    expect(newComp.checkAdjacent(['b2'])).toEqual('a2');
});
